#!/usr/bin/env bash
run_as_user=$1
shift
run_command=$1
shift

max_fd=4
while [ -n "$1" ]
do
    fname=(/tmp/pass-user-pws*/$1)
    exec {fd}< "${fname[@]}"
    env_var="PASS_FD_${1//-/_}"
    export "$env_var"="$fd"
    max_fd=$((fd>max_fd ? fd : max_fd))
    shift
done

sudo -C $((max_fd+1)) -u $run_as_user $run_command
