#+TITLE: dotfiles
These are my dotfiles.  I use this repository as a personal backup and for
synchronization between my machines.
* Setup
  Invoking make will create a symlink in your home directory for each file in
  this directory that starts with a dot.

  The special target for st will download the PKGBUILD from the AUR, clone
  the st repository, apply my and some other patches, build the package and
  finally install it.
* Setup with Nix
  Unfortunately, keyboard configuration is cursed and requires make XKB_LAYOUT` and ` localectl set-x11-keymap my_gb pc105 swapyz "caps:escape,compose:menu"`.
  Debian-based systems are especially annoying and block localectl, there it's best to edit /etc/defaults/keyboard directly.
  - first run: `nix run --extra-experimental-features nix-command --extra-experimental-features flakes -- home-manager --extra-experimental-features nix-command --extra-experimental-features flakes switch --flake .#$USER`
  - all subsequent runs: `home-manager switch --flake .#$USER`
  Swaylock requires pam configuration and is best installed via the system package manager.
  Other system-wide packages: bluez cups udisks2
	everything that has bluetooth, pulse, pipewire, wireplumber, and alsa in its name, like srsly wtf!?
* Contribution
  These are MY dotfiles.  I use this repository as a PERSONAL backup and for
  synchronization between MY machines.

  If you have a great additions in mind, consider creating your own dotfiles
  repository and I will steal it from you.  If you are really kind, open an
  issue and point me to your solution.

  No pull requests.  I will test everything locally and tweak with it a bit,
  then I'll commit it once I'm content.
