#! perl

# Implements a scrollwheel just like in good old vt100's mices

sub simulate_keypress {
    my ($self, $type) = @_; #type: 0:up, 1:down
    
    my $keycode_up = 52;
    my $keycode_down = 26;
    
    my $keycode = 0;
    if ($type eq 0) {
        $keycode = $keycode_up;
    } elsif ($type eq 1) {
        $keycode = $keycode_down;
    } else {
        return;
    }
    
    $self->key_press(0x4,$keycode);
    $self->key_release(0x4,$keycode);
}

sub on_button_release {
    my ($self, $event) = @_;
    
    !$self->current_screen and return ();
    
    if ($event->{button} eq "4") { # scroll up
        $self->simulate_keypress(0);
		return 1;
    } elsif ($event->{button} eq "5") { # scroll down
        $self->simulate_keypress(1);
		return 1;
    }
    
    return ();
}

