#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX
#bspc monitor HDMI1 -d X
bspc monitor VIRTUAL1 -d X

BW=1
WG=12
bspc config border_width $BW
bspc config window_gap $WG
for side in top right bottom left ; do
        bspc config ${side}_padding -$WG
done

bspc config normal_border_color "#141414"
bspc config focused_border_color "#333333"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc rule -a Zathura state=tiled
bspc rule -a Tilda state=floating focus=on locked=on manage=on
bspc rule -a Pinentry state=floating focus=on locked=on manage=on

tilda -h &
conky
$HOME/mpd-libnotify/mpdnotify start
